# Site settings
title: 一万个不回头的方法
SEOTitle: 陈十一的博客 | CheeReus_11
header-img: img/post-bg-os-metro.jpg
email: fanwei1995@hotmail.com
description: "因为痛苦太有价值，因为回忆太珍贵，所以我们更要继续往前走"
keyword: "陈十一, CheeReus_11, iOS, Apple, iPhone"
url: "http://cheereus.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Cheereus/cheereus.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "学会爱人，成为大人"
sidebar-avatar: /img/reus_avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
weibo_username:   CheeReus__11
zhihu_username:     fan-wei-56
github_username:    Cheereus
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   Cheereus




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: Cheereus

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e36515dddd1972d6d97e                            #生成的clientID
  clientSecret: cfc525a98c6e0e0c4399fc82e64ba4226a030e8d    #生成的clientSecret
  repo: cheereus.github.io    #仓库名称
  owner: Cheereus    #github用户名
  admin: Cheereus
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-112164372-1'            # Format: UA-xxxxxx-xx
ga_domain: cheereus.com               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false



# Friends
friends: [
    {
        title: "Github",
        href: "https://github.com/Cheereus"
    },
    {
        title: "Segmentfault",
        href: "https://segmentfault.com/blog/cheereus"
    },
]
